version: '3.8'

services:
  # Application Service
  app:
    container_name: api_assessment
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www
  
  # Web Server Service
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - db
  
  # Database Service
  db:
    image: postgres
    container_name: postgres
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: api_assessment
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin